name: Build Docker + Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag olsonadr/ucl_interview:test
    - name: Run tests
      run: docker run --name ucl_interview --rm olsonadr/ucl_interview:test
